version: '3.8'

services:
  postgresdb:
    image: postgres:13
    container_name: postgres_container
    env_file: app/.dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

        #app:
        # build: ./app
        #container_name: node_app
        # depends_on:
        #      - postgresdb
        #    ports:
        #      - "3000:3000"
        #    env_file: app/.dev.env
    # environment:
    #   DB_HOST: postgresdb
    #   DB_USER: ${DB_USER}
    #   DB_PASSWORD: ${DB_PASSWORD}
    #   DB_NAME: ${DB_NAME}
    #   DB_PORT: 5432
    #    volumes:
    #      - ./app:/usr/src/app
    #  - /usr/src/app/node_modules

volumes:
  postgres_data:

