name: Docker upload image to Yandex Cloud Container Registry

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:

    environment:
      name: yandex-cloud

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v4

    - name: login
      run: |
        echo "${{ secrets.YC_OAUTH_TOKEN }}" | docker login \
          --username oauth \
          --password-stdin \
          cr.yandex

    - name: build_and_push
      run: |
      DATE=date +%d.%m.%Y
      SHORT_SHA=${GITHUB_SHA::7}
      docker build . --file Dockerfile --tag cr.yandex/crp0iuhn6c5se3bdfrsv/test-app:$DATE-$SHORT_SHA
      docker push cr.yandex/crp0iuhn6c5se3bdfrsv/test-app:$DATE-$SHORT_SHA
      working-directory: ./app
